//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pushe.co.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PusheMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PusheMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pushe.co.Resource.PusheMetadata", typeof(PusheMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن اعلان بزرگ.
        /// </summary>
        public static string Notification_Big_Content {
            get {
                return ResourceManager.GetString("Notification_Big_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیتر اعلان بزرگ.
        /// </summary>
        public static string Notification_Big_Title {
            get {
                return ResourceManager.GetString("Notification_Big_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن اعلان کوچک.
        /// </summary>
        public static string Notification_Content {
            get {
                return ResourceManager.GetString("Notification_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین زمان ارسال.
        /// </summary>
        public static string Notification_Eta {
            get {
                return ResourceManager.GetString("Notification_Eta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس آیکون داخلی پوش.
        /// </summary>
        public static string Notification_Icon {
            get {
                return ResourceManager.GetString("Notification_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس عکس بنر.
        /// </summary>
        public static string Notification_Image {
            get {
                return ResourceManager.GetString("Notification_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین رنگ led.
        /// </summary>
        public static string Notification_LED_Color {
            get {
                return ResourceManager.GetString("Notification_LED_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خاموش ماندن led به میلی ثانیه.
        /// </summary>
        public static string Notification_LED_Off {
            get {
                return ResourceManager.GetString("Notification_LED_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان روشن ماندن led به میلی ثانیه.
        /// </summary>
        public static string Notification_LED_On {
            get {
                return ResourceManager.GetString("Notification_LED_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون جایگزین آیکون اپ.
        /// </summary>
        public static string Notification_Notif_Icon {
            get {
                return ResourceManager.GetString("Notification_Notif_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اعلان در اپلیکیشن.
        /// </summary>
        public static string Notification_Show_App {
            get {
                return ResourceManager.GetString("Notification_Show_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صدای هشدار به هنگام دریافت اعلان.
        /// </summary>
        public static string Notification_Sound_Url {
            get {
                return ResourceManager.GetString("Notification_Sound_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن نوار اعلان.
        /// </summary>
        public static string Notification_Ticker {
            get {
                return ResourceManager.GetString("Notification_Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیتر اعلان کوچک.
        /// </summary>
        public static string Notification_Title {
            get {
                return ResourceManager.GetString("Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به کاربران مشترک اپها یک پیام ارسال شود.
        /// </summary>
        public static string Notification_Unique {
            get {
                return ResourceManager.GetString("Notification_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلان نمایش داده شود یا خیر.
        /// </summary>
        public static string Notification_Visibility {
            get {
                return ResourceManager.GetString("Notification_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روشن شدن صفحه نمایش به هنگام دریافت پیام.
        /// </summary>
        public static string Notification_Wake_Screen {
            get {
                return ResourceManager.GetString("Notification_Wake_Screen", resourceCulture);
            }
        }
    }
}
